part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const CATEGORY = _Paths.CATEGORY;
  static const ListDonation = _Paths.ListDonation;
  static const KONFIRMASI_TRANSFER = _Paths.KONFIRMASI_TRANSFER;
  static const SEND_MONEY = _Paths.SEND_MONEY;
  static const SEND_MONEY2 = _Paths.SEND_MONEY2;
  static const SPLASH_SCREEN = _Paths.SPLASH_SCREEN;
  static const ON_BOARDING_PAGE = _Paths.ON_BOARDING_PAGE;
  static const PAYMENT_ACCOUNT_PAGE = _Paths.PAYMENT_ACCOUNT_PAGE;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const AGGREMENT = _Paths.AGGREMENT;
  static const OTP = _Paths.OTP;
  static const EMAIL_VERIFICATION = _Paths.EMAIL_VERIFICATION;
  static const FORGOTPASS_VERIFICATION = _Paths.FORGOTPASS_VERIFICATION;
  static const RESET_PASS = _Paths.RESET_PASS;
  static const REPORT = _Paths.REPORT;
  static const PROFILE = _Paths.PROFILE;
  static const NAVIGATION = _Paths.NAVIGATION;
  static const DONATION_DETAIL_PAGE = _Paths.DONATION_DETAIL_PAGE;
  static const PARTICIPANT_PAGE = _Paths.PARTICIPANT_PAGE;
  static const PAYMENT = _Paths.PAYMENT;
  static const LIST_PAYMENT = _Paths.LIST_PAYMENT;
  static const PAYMENT_SUCCESS = _Paths.PAYMENT_SUCCESS;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const CHAT = _Paths.CHAT;
  static const MESSAGE = _Paths.MESSAGE;
  static const QURAN = _Paths.QURAN;
  static const LIST_USER = _Paths.LIST_USER;
  static const CATEGORIES = _Paths.CATEGORIES;
  static const ADMIN_PANEL = _Paths.ADMIN_PANEL;
  static const CONTRIBUTOR_ADMIN = _Paths.CONTRIBUTOR_ADMIN;
  static const CHARITY_ADMIN = _Paths.CHARITY_ADMIN;
  static const UPLOAD = _Paths.UPLOAD;
  static const COMPANIES = _Paths.COMPANIES;
  static const TRANSACTIONS = _Paths.TRANSACTIONS;
  static const BANK_ADMIN = _Paths.BANK_ADMIN;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const CATEGORY = '/category';
  static const ListDonation = '/listDonation';
  static const KONFIRMASI_TRANSFER = '/confirmationTransfer';
  static const SEND_MONEY = '/sendMoney';
  static const SEND_MONEY2 = '/sendMoney2';
  static const SPLASH_SCREEN = '/splash-screen';
  static const ON_BOARDING_PAGE = '/on-boarding-page';
  static const PAYMENT_ACCOUNT_PAGE = '/payment-account-page';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const AGGREMENT = '/aggrement';
  static const OTP = '/otp';
  static const EMAIL_VERIFICATION = '/email-verification';
  static const FORGOTPASS_VERIFICATION = '/forgotpass-verification';
  static const RESET_PASS = '/reset-pass';
  static const PROFILE = '/profile';
  static const NAVIGATION = '/navigation';
  static const PARTICIPANTS = '/participants';
  static const REPORT = '/report';
  static const DONATION_DETAIL_PAGE = '/donation-detail-page';
  static const PARTICIPANT_PAGE = '/participant-page';
  static const PAYMENT = '/payment';
  static const LIST_PAYMENT = '/list-payment';
  static const PAYMENT_SUCCESS = '/payment-success';
  static const NOTIFICATION = '/notification';
  static const CHAT = '/chat';
  static const MESSAGE = '/message';
  static const QURAN = '/quran';
  static const LIST_USER = '/list-user';
  static const CATEGORIES = '/categories';
  static const ADMIN_PANEL = '/admin-panel';
  static const CONTRIBUTOR_ADMIN = '/contributor-admin';
  static const CHARITY_ADMIN = '/charity-admin';
  static const UPLOAD = '/upload';
  static const COMPANIES = '/companies';
  static const TRANSACTIONS = '/transactions';
  static const BANK_ADMIN = '/bank-admin';
}
